### ISSUE TITLE
link: duplicated definition of symbol addMulVVWx, from filippo.io/bigmod and crypto/internal/bigmod

### ISSUE THREAD

**Issue by johncmerfeld** [FiloSottile/bigmod#1]
Our project imports both `filippo.io/bigmod` and the standard library's `crypto`. On the latest Go version, we're unable to build to to this conflict:

```
link: duplicated definition of symbol addMulVVWx, from filippo.io/bigmod and crypto/internal/bigmod
```

What is the best way to resolve this? We need this library to support constant-time cryptographic operations but elsewhere we use various public `crypto` functions.

**Comment by FiloSottile** [comment]
Thank you for the report! Fixed in v0.0.3.
